# Generated by Django 6.0.4 on 2026-04-14 05:57

import django.core.validators
import education.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_category_alter_course_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, help_text='Поддерживаются форматы: JPG, PNG, GIF. Максимальный размер: 5 МБ', null=True, upload_to='teachers/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), education.models.validate_image_size], verbose_name='Фото'),
        ),
    ]
